sprint 8 homework
katja-balakireva/java-filmorate pull request #1
Opened 2022-07-11 14:18 UTC by katja-balakireva

2022-07-11 17:17 UTC, kukolev requested changes

2022-07-11 17:17 UTC, kukolev commented on src/main/java/ru/yandex/practicum/controllers/FilmController.java
> +        LocalDate releaseDate = LocalDate.of(1895, Month.DECEMBER, 28);
Объект LocalDate.of(1895, 12, 28) лучше сделать константой, чтобы не приходилось всякий раз создавать при валидации.

2022-07-11 17:17 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerValidationTests.java
> +    FilmController filmController;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-07-11 17:17 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/UserControllerValidationTests.java
> +    UserController userController;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-07-11 17:20 UTC, kukolev requested changes

2022-07-11 17:20 UTC, kukolev commented on src/main/java/ru/yandex/practicum/controllers/ValidationException.java
> +public class ValidationException extends Exception {
По своей сути это исключение должно быть непроверяемым, т.к. в коде это исключение нигде не обрабатывается.

2022-07-11 20:07 UTC, katja-balakireva commented on src/main/java/ru/yandex/practicum/controllers/FilmController.java
> +        LocalDate releaseDate = LocalDate.of(1895, Month.DECEMBER, 28);
+ исправлено

2022-07-11 20:10 UTC, softpaw-mango-cat commented on src/main/java/ru/yandex/practicum/controllers/ValidationException.java
> +public class ValidationException extends Exception {
исправлено :)

2022-07-12 07:28 UTC, kukolev approved these changes

2022-07-12 19:34 UTC, merged