Sprint 9 homework
katja-balakireva/java-filmorate pull request #2
Opened 2022-07-20 20:14 UTC by katja-balakireva

2022-07-21 07:46 UTC, kukolev requested changes

2022-07-21 07:46 UTC, kukolev commented on src/main/java/ru/yandex/practicum/controllers/FilmController.java
> +        Set<Film> filmList = filmService.getFilmStorage().getAll();
Сервис должен быть единой точкой входа, в которой выполняется бизнес-логика. Здесь, фактически, сервис просто является контейнером для хранилища, а логика вынесена в контроллер. Это нужно исправить.

Аналогично нужно исправить ниже.

2022-07-21 07:46 UTC, kukolev commented on src/main/java/ru/yandex/practicum/controllers/UserController.java
> +        Set<User> userList = userService.getUserStorage().getAll();
Сервис должен быть единой точкой входа, в которой выполняется бизнес-логика. Здесь, фактически, сервис просто является контейнером для хранилища, а логика вынесена в контроллер. Это нужно исправить.

Аналогично нужно исправить ниже.

2022-07-21 07:46 UTC, kukolev commented on src/main/java/ru/yandex/practicum/controllers/UserController.java
> +    UserService userService;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-07-21 07:46 UTC, kukolev commented on src/main/java/ru/yandex/practicum/controllers/FilmController.java
> +    FilmService filmService;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-07-21 07:46 UTC, kukolev commented on src/main/java/ru/yandex/practicum/service/FilmService.java
> +    FilmStorage filmStorage;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-07-21 07:46 UTC, kukolev commented on src/main/java/ru/yandex/practicum/service/UserService.java
> +    UserStorage userStorage;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-07-21 07:46 UTC, kukolev commented on src/main/java/ru/yandex/practicum/service/UserService.java
> +@Getter
Геттеры не нужны в сервисах, т.к. нет необходимости возвращать зависимости сервиса. Вместо этого сервис должен предоставлять методы для работы бизнес-логики.

2022-07-21 07:46 UTC, kukolev commented on src/main/java/ru/yandex/practicum/service/FilmService.java
> +@Getter
Геттеры не нужны в сервисах, т.к. нет необходимости возвращать зависимости сервиса. Вместо этого сервис должен предоставлять методы для работы бизнес-логики.

2022-07-21 07:46 UTC, kukolev commented on src/main/java/ru/yandex/practicum/storage/InMemoryFilmStorage.java
> +            log.warn("Ошибка валидации названия фильма");
При логировании лучше добавлять информацию о текущих значениях параметров, чтобы при анализе было понятно о чем идет речь. Здесь будет полезно добавить значение переменной film.

2022-07-21 07:46 UTC, kukolev commented on src/main/java/ru/yandex/practicum/storage/InMemoryUserStorage.java
> +            log.warn("Ошибка валидации email пользователя");
При логировании лучше добавлять информацию о текущих значениях параметров, чтобы при анализе было понятно о чем идет речь. Здесь будет полезно добавить значение переменной user

2022-07-22 16:42 UTC, kukolev requested changes

2022-07-22 16:42 UTC, kukolev commented on src/main/java/ru/yandex/practicum/storage/InMemoryFilmStorage.java
> +    private boolean validateFilm(Film film) throws ValidationException {
Валидацию принято делать в сервисах, т.к. это задача сервиса проверить, можно ли вообще работать с такими данными. Нужно перенести валидацию в сервис.

2022-07-22 16:42 UTC, kukolev commented on src/main/java/ru/yandex/practicum/storage/InMemoryUserStorage.java
> +    private boolean validateUser(User user) throws ValidationException {
Валидацию принято делать в сервисах, т.к. это задача сервиса проверить, можно ли вообще работать с такими данными. Нужно перенести валидацию в сервис.

2022-07-22 16:42 UTC, kukolev commented on src/main/java/ru/yandex/practicum/storage/InMemoryUserStorage.java
> +            if (u.getEmail().equals(user.getEmail())) {
Нарушение кодстайла: Переменные должны называться так, чтобы из названия можно было понять, за что отвечает переменная. Так код будет понятней при анализе.

2022-07-22 16:42 UTC, kukolev commented on src/main/java/ru/yandex/practicum/storage/InMemoryUserStorage.java
> +            for (User u : users) {
Нарушение кодстайла: Переменные должны называться так, чтобы из названия можно было понять, за что отвечает переменная. Так код будет понятней при анализе.

2022-07-22 16:42 UTC, kukolev commented on src/main/java/ru/yandex/practicum/storage/InMemoryUserStorage.java
> +        for (User u : users) {
Нарушение кодстайла: Переменные должны называться так, чтобы из названия можно было понять, за что отвечает переменная. Так код будет понятней при анализе.

2022-07-23 04:15 UTC, katja-balakireva commented on src/main/java/ru/yandex/practicum/storage/InMemoryFilmStorage.java
> +    private boolean validateFilm(Film film) throws ValidationException {
+ исправлено

2022-07-23 04:15 UTC, katja-balakireva commented on src/main/java/ru/yandex/practicum/storage/InMemoryUserStorage.java
> +    private boolean validateUser(User user) throws ValidationException {
+ исправлено

2022-07-23 16:17 UTC, kukolev approved these changes

2022-07-23 17:42 UTC, merged