Add database
katja-balakireva/java-filmorate pull request #7
Opened 2022-08-14 09:38 UTC by katja-balakireva

2022-08-14 21:51 UTC, kukolev requested changes

2022-08-14 21:51 UTC, kukolev commented on db/filmorate.trace.db
> +2022-08-04 16:30:52 jdbc[3]: exception
Этот файл не относится к исходному коду проекта и не нужен здесь. Файл нужно удалить.

Также нужно удалить файл filmorate.mv.db по той-же причине.

2022-08-15 15:29 UTC, kukolev requested changes

2022-08-15 15:29 UTC, kukolev commented on src/main/java/ru/yandex/practicum/service/LikeService.java
> +    public boolean validateLikes(long filmId, long likeId) {
Метод нужно сделать приватным, т.к. он является вспомогательными и не нужно, чтобы к нему был доступ извне.

2022-08-15 15:29 UTC, kukolev commented on src/main/java/ru/yandex/practicum/service/MpaService.java
> +@Slf4j
Эта аннотация не нужна, т.к. нет логов. Лучше добавить логи или убрать аннотацию.

2022-08-15 15:46 UTC, katja-balakireva commented on src/main/java/ru/yandex/practicum/service/LikeService.java
> +    public boolean validateLikes(long filmId, long likeId) {
Исправлено

2022-08-15 15:47 UTC, katja-balakireva commented on src/main/java/ru/yandex/practicum/service/MpaService.java
> +@Slf4j
Исправлено

2022-08-16 06:37 UTC, kukolev approved these changes

2022-08-16 06:51 UTC, merged